/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:30eab124-87e2-46d5-a9e7-be2f54d8275f",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_sMMR0Je9P",
    "aws_user_pools_web_client_id": "6rkvt7urs8qtv7hs0ok7golgl0",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://ksykxktmlvcctk7dl5ajus7mrm.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-4sukyqnl5rfpjd3w43b6jnwcge",
    "aws_user_files_s3_bucket": "twitter1qty163312-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
